"""
Seed data — 20 movies used across all demos and tests.
"""

MOVIES = [
    {"id": "m01", "title": "Inception", "genre": "sci-fi",
     "year": 2010, "director": "Christopher Nolan",
     "description": "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a CEO. Layers of dreams within dreams create a mind-bending heist thriller."},
    {"id": "m02", "title": "The Dark Knight", "genre": "action",
     "year": 2008, "director": "Christopher Nolan",
     "description": "Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos. A gritty crime thriller exploring morality, chaos, and heroism."},
    {"id": "m03", "title": "Interstellar", "genre": "sci-fi",
     "year": 2014, "director": "Christopher Nolan",
     "description": "A group of astronauts travel through a wormhole near Saturn in search of a new home for humanity. Explores relativity, love, and the fabric of space-time."},
    {"id": "m04", "title": "The Matrix", "genre": "sci-fi",
     "year": 1999, "director": "Lana Wachowski",
     "description": "A computer hacker discovers that reality is a simulated world created by machines. He joins rebels fighting the AI overlords to free humanity."},
    {"id": "m05", "title": "Parasite", "genre": "thriller",
     "year": 2019, "director": "Bong Joon-ho",
     "description": "A poor family schemes to become employed by a wealthy family by infiltrating their household. A darkly comic thriller about class inequality."},
    {"id": "m06", "title": "Pulp Fiction", "genre": "thriller",
     "year": 1994, "director": "Quentin Tarantino",
     "description": "Interlocking stories of Los Angeles criminals, a boxer, and a pair of diner bandits. Non-linear narrative with sharp dialogue and unexpected violence."},
    {"id": "m07", "title": "The Shawshank Redemption", "genre": "drama",
     "year": 1994, "director": "Frank Darabont",
     "description": "A banker sentenced to life in Shawshank prison finds friendship and hope through decency in a corrupt system. A story of patience, hope, and perseverance."},
    {"id": "m08", "title": "Spirited Away", "genre": "animation",
     "year": 2001, "director": "Hayao Miyazaki",
     "description": "A girl gets trapped in a spirit world and must work in a bathhouse to free her parents, who have been transformed into pigs."},
    {"id": "m09", "title": "Get Out", "genre": "horror",
     "year": 2017, "director": "Jordan Peele",
     "description": "A Black man visits his white girlfriend's family estate and uncovers a disturbing secret. A social thriller about racism in modern America."},
    {"id": "m10", "title": "Mad Max: Fury Road", "genre": "action",
     "year": 2015, "director": "George Miller",
     "description": "In a post-apocalyptic wasteland, a woman rebels against a tyrant in a high-octane chase across the desert. Non-stop practical-effects action."},
    {"id": "m11", "title": "Arrival", "genre": "sci-fi",
     "year": 2016, "director": "Denis Villeneuve",
     "description": "A linguist is recruited to communicate with alien spacecraft that have appeared around the world. Language, time, and memory converge in a quiet, emotional story."},
    {"id": "m12", "title": "Her", "genre": "sci-fi",
     "year": 2013, "director": "Spike Jonze",
     "description": "A lonely writer develops a romantic relationship with an AI operating system. A meditation on love, loneliness, and the nature of consciousness."},
    {"id": "m13", "title": "Coco", "genre": "animation",
     "year": 2017, "director": "Lee Unkrich",
     "description": "A young boy travels to the Land of the Dead to find his musician great-great-grandfather. A vibrant celebration of Mexican culture, family, and memory."},
    {"id": "m14", "title": "Knives Out", "genre": "thriller",
     "year": 2019, "director": "Rian Johnson",
     "description": "A detective investigates the death of a patriarch of a wealthy family. A sharp whodunit that subverts the genre's conventions."},
    {"id": "m15", "title": "The Godfather", "genre": "drama",
     "year": 1972, "director": "Francis Ford Coppola",
     "description": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son. An epic saga of power, family loyalty, and corruption."},
    {"id": "m16", "title": "Everything Everywhere All at Once", "genre": "sci-fi",
     "year": 2022, "director": "Daniel Kwan",
     "description": "An exhausted Chinese-American woman discovers she can access skills from parallel universes and must fight a powerful villain to save the multiverse."},
    {"id": "m17", "title": "Hereditary", "genre": "horror",
     "year": 2018, "director": "Ari Aster",
     "description": "After the family matriarch dies, her daughter and family uncover dark secrets about their ancestry and are haunted by a sinister supernatural force."},
    {"id": "m18", "title": "Blade Runner 2049", "genre": "sci-fi",
     "year": 2017, "director": "Denis Villeneuve",
     "description": "A new blade runner discovers a secret that could plunge society into chaos. A visually stunning neo-noir about identity, humanity, and memory."},
    {"id": "m19", "title": "12 Angry Men", "genre": "drama",
     "year": 1957, "director": "Sidney Lumet",
     "description": "Twelve jurors deliberate the fate of a young man accused of murder. A tense examination of reasonable doubt, bias, and civic duty."},
    {"id": "m20", "title": "Avengers: Endgame", "genre": "action",
     "year": 2019, "director": "Anthony Russo",
     "description": "The Avengers assemble one final time to undo Thanos's destruction of half the universe. The culmination of a decade-long cinematic saga."},
]

USERS = [
    {"id": "u01", "username": "alice_w", "email": "alice@cineai.dev"},
    {"id": "u02", "username": "bob_k",   "email": "bob@cineai.dev"},
    {"id": "u03", "username": "carol_m", "email": "carol@cineai.dev"},
    {"id": "u04", "username": "dave_r",  "email": "dave@cineai.dev"},
    {"id": "u05", "username": "eva_t",   "email": "eva@cineai.dev"},
]

RATINGS = [
    ("u01", "m01", 5.0, "Mind-blowing layers"),
    ("u01", "m03", 4.5, "Visually stunning"),
    ("u01", "m04", 5.0, "Changed my view of reality"),
    ("u01", "m11", 4.0, "Beautiful and quiet"),
    ("u01", "m12", 3.5, "Thought-provoking"),
    ("u02", "m02", 5.0, "Best superhero film"),
    ("u02", "m06", 4.5, "Classic Tarantino"),
    ("u02", "m10", 4.0, "Incredible action"),
    ("u02", "m20", 4.5, "Epic conclusion"),
    ("u03", "m07", 5.0, "Most moving film ever"),
    ("u03", "m15", 5.0, "Timeless masterpiece"),
    ("u03", "m19", 4.5, "Riveting from start to finish"),
    ("u04", "m05", 5.0, "Perfectly crafted thriller"),
    ("u04", "m09", 4.5, "Terrifying social commentary"),
    ("u04", "m14", 4.0, "Fun genre subversion"),
    ("u05", "m08", 5.0, "Magical and beautiful"),
    ("u05", "m13", 4.5, "Made me cry"),
    ("u05", "m16", 5.0, "Completely original"),
    # Cross-user ratings on popular films
    ("u02", "m01", 4.5, "Incredible heist concept"),
    ("u03", "m01", 4.0, "Dense but rewarding"),
    ("u04", "m01", 5.0, "Perfect sci-fi"),
    ("u01", "m07", 4.5, "Deeply emotional"),
    ("u02", "m07", 5.0, "Absolute classic"),
    ("u05", "m07", 4.5, "Beautifully told"),
]
